### ISSUE TITLE
operator being used instead of publisher in SensorML publisher classifier

### ISSUE THREAD

**Issue by emiliom** [ioos/sos-injector-db#17]
I've examined a couple of i52n SOS instances (NANOOS and CeNCOOS). In the SensorML classifiers, I believe the publisher entry is not being used correctly. Currently it's being populated with the same entity/institution listed -- correctly -- in the Contacts as the operator. Instead, it should be populated with the same entity/institution listed in the Contacts as the publisher (eg, the RA).

(I'm assuming this is an `sos-injector-db` issue, not directly a `i52n-sos` issue)

Here are some references:
- http://ioos.github.io/sos-guidelines/template/SML-DescribeSensor-Station/
- https://github.com/ioos/vocabularies/blob/master/README.md
- http://mmisw.org/ont/ioos/definition/publisher
- http://mmisw.org/ont/ioos/definition/operator

**Comment by shane-axiom** [comment]
From what I can't tell this is not longer a code issue (and hasn't been for a long time). I suspect that there was a configuration problem long ago when these stations were first registered with the SOSes, and since the SML doesn't get updated these issues never get corrected.

I added an [issue to sos-injector](https://github.com/ioos/sos-injector/issues/5) to implement `UpdateSensorDescription`, which should update these old SensorMLs with corrected info.

I'm closing this for now in favor of the sos-injector issue. Should be ready for the i52n-sos 1.2 release at the end of September.

**Comment by emiliom** [comment]
Great. Looks like you were busy with i52n sos stuff! I'll report back eventually, when I've had a chance to upgrade and test. Maybe by late September, more likely in October.
